# Generated by Django 2.2.5 on 2020-09-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_title', models.CharField(max_length=100, verbose_name='Gallery title')),
                ('gallery_description', models.TextField(verbose_name='Gallery description')),
                ('gallery_Image', models.ImageField(upload_to='galley_images', verbose_name='Gallery Image')),
            ],
        ),
    ]
